// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

/**
 * Health status payload returned by the health endpoint.
 */
export type Health = {
    /**
     * Database connectivity indicator.
     */
    db: string;
    /**
     * Overall service status.
     */
    status: string;
    /**
     * Crate version, set at compile time.
     */
    version: string;
};

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/healthz';
};

export type HealthzErrors = {
    /**
     * Service degraded
     */
    503: Health;
};

export type HealthzError = HealthzErrors[keyof HealthzErrors];

export type HealthzResponses = {
    /**
     * Service healthy
     */
    200: Health;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];
